# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tests/test_row.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "tests/test_row.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14tests/test_row.proto\x12\x05tests"5\n\x0cTestTableRow\x12\x11\n\tcity_name\x18\x01 \x01(\t\x12\x12\n\npopulation\x18\x02 \x01(\x05"A\n\nAirQuality\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x0c\n\x04temp\x18\x02 \x01(\x05\x12\x10\n\x08humidity\x18\x03 \x01(\x03"7\n\nNestedData\x12\x15\n\rnested_string\x18\x01 \x01(\t\x12\x12\n\nnested_int\x18\x02 \x01(\x05"\xc5\x02\n\x0e\x41llTypesRecord\x12\x14\n\x0cstring_field\x18\x01 \x01(\t\x12\x13\n\x0bint32_field\x18\x02 \x01(\x05\x12\x13\n\x0bint64_field\x18\x03 \x01(\x03\x12\x13\n\x0b\x66loat_field\x18\x04 \x01(\x02\x12\x14\n\x0c\x64ouble_field\x18\x05 \x01(\x01\x12\x12\n\nbool_field\x18\x06 \x01(\x08\x12\x13\n\x0b\x62ytes_field\x18\x07 \x01(\x0c\x12\x17\n\x0frepeated_string\x18\x08 \x03(\t\x12\x16\n\x0erepeated_int32\x18\t \x03(\x05\x12\x17\n\x0frepeated_double\x18\n \x03(\x01\x12)\n\x0enested_message\x18\x0b \x01(\x0b\x32\x11.tests.NestedData\x12*\n\x0frepeated_nested\x18\x0c \x03(\x0b\x32\x11.tests.NestedData'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tests.test_row_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TESTTABLEROW"]._serialized_start = 31
    _globals["_TESTTABLEROW"]._serialized_end = 84
    _globals["_AIRQUALITY"]._serialized_start = 86
    _globals["_AIRQUALITY"]._serialized_end = 151
    _globals["_NESTEDDATA"]._serialized_start = 153
    _globals["_NESTEDDATA"]._serialized_end = 208
    _globals["_ALLTYPESRECORD"]._serialized_start = 211
    _globals["_ALLTYPESRECORD"]._serialized_end = 536
# @@protoc_insertion_point(module_scope)
