# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecord.proto\x12\x08\x65xamples\"A\n\nAirQuality\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x0c\n\x04temp\x18\x02 \x01(\x05\x12\x10\n\x08humidity\x18\x03 \x01(\x03')



_AIRQUALITY = DESCRIPTOR.message_types_by_name['AirQuality']
AirQuality = _reflection.GeneratedProtocolMessageType('AirQuality', (_message.Message,), {
  'DESCRIPTOR' : _AIRQUALITY,
  '__module__' : 'record_pb2'
  # @@protoc_insertion_point(class_scope:examples.AirQuality)
  })
_sym_db.RegisterMessage(AirQuality)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AIRQUALITY._serialized_start=26
  _AIRQUALITY._serialized_end=91
# @@protoc_insertion_point(module_scope)
